__author__ = 'apeckys'


data = 'CTGGGTGTCACTCTCCCCCGAGAACATGGGGGCTCGAATATCAAGGACGAATAGTTTGAGCAGGACGCGTTATTTGACTTCGTTAGTGTGAGTTGCATCCGACCTATATACATTTTGGTCTTATAGAGAAGGTGCGAAGTCATCCTTCCCTCGTCCAAGAGTGCCATCGCGACCTATTGTGGAGAGCAAATGCCCTAGCATCCACATCAATCCTCTACCCTGCCCGTGCTTGATGCCGTAGTGTACAACGGAAGCATGCGCTCATTTGGGGGAATCAACCGCTGCGACTGTGATCCGCCACCTCGTACACGCAAAATCCTCTTGTCGCATGATCATAATTATAGAAGGTGGGACCACCGGCACAGGAGCGTGCCCAAATCGCCTGGAGACTGGTTTAGTGATGGGGCTAAGAAGGCTCTTCTCGCTCAGTATCTCCGTTGACCTGAACTTCACGCTCCCTATGCCGCGCATTTGCTCACCGATCATTAGGATTCCTGAAAGTCCGCATGGGTGCCGTTCTTCGACGGTGGTTGCAGTGAACGACGTACGAGCTGGGATAGAGGAGAGCTATAAGCGGTGGGCACCAATACATGTCCAAGCTACTACAACGCATGGAATGCCTACCGTGTACTGGAATGGATTACGTCGGATTTCTGCACACTCCCTCCGTATAGGCTCTGTTCTGAGTGCCATGGGCGGAGGGCATCAATGGCTCCAGATGTGATCAGCGTCTTTCTTGGTGCCAGCAACGCCGGAGGATGTCGGCCCATATCACCGCGGCTTAAAACGATGAAGAATAGTTCCGGTCACGACCTGGCCTCTATCTGGTCCACAACTTATTAGAGGTAATTTGCGCGTGAGCGAGGCCCATAGTCAGAAGTAACGGCCGCACCGAAACGTTAGACTCGACCGTTCCAATGCACGCAACCCTCCTAGAGAGCTAGTG'

A = 0
C = 0
G = 0
T = 0

for char in data:
    if char == 'A':
        A += 1
    elif char == 'C':
        C += 1
    elif char == 'G':
        G += 1
    elif char == 'T':
        T += 1


print '%i %i %i %i' % (A, C, G, T)
