__author__ = 'apeckys'
import re



def __main():
    data_set = 'CAGAATATAGGATATAGGTACATATAGGGATATAGGTATATAGGATATAGGTACAGGTAGATATAGGATATAGGGAAGGATATAGGCATATAGGATATAGGCTGAATATAGGATATAGGATATATATAGGATATAGGGATATAGGTATATAGGATATAGGATATAGGGAATATAGGTCACGGTAAGAGACACCGATATAGGCTATATAGGAGAATATAGGATCGTCCTTGCATATAGGAAGATATAGGATATATAGGTCCATATAGGACGGTATATAGGAGATATAGGATATAGGTATATAGGCGATATAGGGATATAGGAATATAGGATATAGGATATAGGGTATATAGGGAATATAGGCCACGCATATAGGGGATATAGGGGATATAGGCGGGATATAGGGTAGATATATAGGGATATAGGTTATATAGGATCGTAATGATCACTCATATAGGCCTATATAGGACGCGATATAGGCCAATATAGGCATATAGGGGTAGCCAGAATCTTGATATAGGGTATATAGGATATAGGCCCCTGTACGAATATAGGGGATATAGGTATATAGGATGATATAGGACAATATAGGGATATAGGTAGAGATATAGGCTATATAGGGGGACAAATATATAGGCAAAACGAATATAGGCATATAGGATATAGGTCATATAGGATATAGGCAGCAACCTATATAGGGTATATAGGATATAGGCCAATATAGGCTATATAGGGTGATATAGGGGAGATATAGGATATAGGACGGGGCGCATATAGGAAGTGATATAGGATATAGGAACTCATCACCATATAGGTGACATATAGGAATATAGGACGGATATAGGACCATATAGGCAAGTATATGCAATATAGGATATAGG'
    lookup = 'ATATAGGAT'
    result = []
    match = re.finditer(lookup,data_set)

    for m in match:
        result.append(str(m.start() + 1))

    print ' '.join(result)



if __name__ == '__main__':
    __main()

