__author__ = 'apeckys'


data = 'TGCCGAAGGAAAACCAACCGAATTCAGACTCCGAACGCCTGAAAAACCCAAACTAAACGCTATACGCCGACGCGAAACAATGTATGACGAAACGCAGTCGAAACAGTTGGCGGCCTCGATGCCGAGAATAGCCTTTTATTAGCAGTTCTGTGTGCGCCGGAAGGTTAAATTTGTCTCGACCTCTTTGTCCGTAAGACGGGCGTCTACTTAGCTCTCACCAACGCACCTTATCGCCCTCGGAAAATTATAATTCGAATCACTTCTGTACCGCTGTCGTTTAAATTCTTGACCACTGTTGGTGCCGCAGTGGGCGCGTTTTAATCGGTACGACTCACGATCCTTGACCTTAGTTCAATACTTACCCGAATCGTGGCGGCAAGTGATGCATGCCCCAGGTAACCGATGCTGACTAGAGCTCAACGCTGTATCCAAAAACTTCCAGGAGCAGAACTACTAAGCTGTAATCTTTGCCTTCTCAGGTCCAACGCCTGTGAGGCGTTTCTGGGCCAATATCCAAGTGCTCGAGTCCATTTAACACATGACCTCGGCCTTGGAAAGTGCAACTCCCTTACCTATGAAGACAAGCTAACCCGTGGTGTGTCCACGGTCGAATCAAAATTCGCAACAAAGCTGGGCGTTTAGCGTAGCAGGGAGAAGAGTGTCTAACCCTGACGACTAGCGGAACACGCGATGAACAGTCGTAGACATCGCATAAGAGAGTGAGGTTAAGAAGTTTATTTCCATTCTATATCTTGAGCATGCCGTGTAGGTTAAGATTTTCACCAAGGATGTAATAGTGTCTGGGGATACTGTTAAACAGTGAGCACTCATGGTTCGTAGAAACCGTGACCACAGACGATATTCCGGGGTATACTCTGTTCCGCCGCGAAGGCGGGTAAGGTAAGTGGACTATGATAACTAGACTGAAGATTAAGCATGTGGCGATCTATGCGTCAGCTCTCACCGTAATAATAAGAA'

new_data = data[::-1]

output = []



for char in new_data:
    if char == 'A':
        output.append('T')
    elif char == 'T':
        output.append('A')
    elif char == 'C':
        output.append('G')
    elif char == 'G':
        output.append('C')

print ''.join(output)